# Generated by Django 3.2.1 on 2021-05-20 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_name', models.TextField()),
                ('goals_id', models.IntegerField()),
                ('created_by', models.TextField()),
                ('moved_by', models.TextField()),
                ('owner', models.TextField()),
                ('goals_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kayodescrumy.goalstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.TextField()),
                ('moved_by', models.TextField()),
                ('moved_from', models.TextField()),
                ('moved_to', models.TextField()),
                ('time_to_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kayodescrumy.scrumygoals')),
            ],
        ),
    ]
