# Generated by Django 3.2.1 on 2021-05-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayodescrumy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='goals_id',
            new_name='goal_id',
        ),
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='goals_name',
            new_name='goal_name',
        ),
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='goals_status',
            new_name='goal_status',
        ),
    ]
